### ISSUE TITLE
Install of 0.3.2 fails due to missing cython

### ISSUE THREAD

**Issue by renefritze** [PyMumps/pymumps#15]
Creating a fresh virtualenv and trying to install pymumps fails.

```bash
python -m venv /tmp/mumps
. /tmp/mumps/bin/activate
python -m pip install pymumps

Collecting pymumps
  Using cached PyMUMPS-0.3.2.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-adykwjrf/pymumps_a229b08a713041b2b0a464a7e87330c6/setup.py", line 6, in <module>
          import Cython
      ModuleNotFoundError: No module named 'Cython'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-adykwjrf/pymumps_a229b08a713041b2b0a464a7e87330c6/setup.py", line 8, in <module>
          raise ImportError('''
      ImportError:
      Cython is required for building this package. Please install using
      
          pip install cython
      
      or upgrade to a recent PIP release.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by nil-is-lin** [comment]
I meet the same problem, seems no methods to overcome it ?
